### PR TITLE
Added setContentType public method to TokenClient

### PR DESCRIPTION
**Pull request by FerhanGit**

### CODE REVIEW

**Comment by mpwaldhorst** [comment]
Hi @FerhanGit ,
Thank you for creating this pull request.
Could you elaborate on the need for this change?

When looking at the specification of OpenID Connect the token endpoint is specified as follows:
"...The Client sends the parameters to the Token Endpoint using the HTTP POST method and the Form Serialization, per Section 13.2, as described in Section 4.1.3 of OAuth 2.0 [RFC6749]..."
http://openid.net/specs/openid-connect-core-1_0.html#TokenRequest

Based on this I'm not sure it should be possible to change the request content type for token requests.
Please let me know what you think.

**Comment by FerhanGit** [comment]
Hi and thank you for your quick response!

I checked the provided documentation and there is an example which uses "Content-Type: application/x-www-form-urlencoded" 

http://openid.net/specs/openid-connect-core-1_0.html#TokenRequest

The following is a non-normative example of a Token Request (with line wraps within values for display purposes only):

  POST /token HTTP/1.1
  Host: server.example.com
  Content-Type: application/x-www-form-urlencoded
  Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

  grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
    &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb

- this is what I want too, but the library doesn't sent "Content-Type" header for /token calls at all.

The code that initialize the token client
(https://github.com/Rehyved/openid-connect-client-php/blob/master/src/Rehyved/OpenId/Client/Token/TokenClient.php#L34)
sets only the "Accept" header and then nowhere is set "Content-Type" and therefore the requests are sent without it:

$this->httpRequest = HttpRequest::create($address)->accept("application/json");

It will be best if I can explicitly define the "Content-Type" as shown on the pull request.
Thank you!

**Comment by mpwaldhorst** [comment]
@FerhanGit Thank you, I got confused by the accept header setting in the constructor.
I agree that the content type should be set to `application/x-www-form-urlencoded`. 
However, I think this should not be something that can be changed through a setter as it is required by the spec to be that specific type.

Instead I would like to change line **132** where the http request is posted to also set the Content Type header appropriately:
```
$response = $this->httpRequest->contentType("application/x-www-form-urlencoded
")->post("", $form);
```

**Comment by FerhanGit** [comment]
Hi, of course. It is fine for me the solution to add the Content-type as you proposed. Please let me know if you could make that change as soon as possible. Thank you once again!
P.S. : Is there a way to decode the JWT with your library, so to have all the claims human readable?
Have a good evening.

**Comment by mpwaldhorst** [comment]
Hi @FerhanGit ,
I just tagged a new version ([0.1.5](https://github.com/Rehyved/openid-connect-client-php/releases/tag/0.1.5)).
This version includes the discussed changes to set the application/x-www-form-urlencoded Content-Type header.

This is now also fixed in TokenClient and all other clients where this was missing.
Please let me know if this does not behave as expected for you.

Regarding parsing the JWT token take a look at the `TokenValidator` class. This class will check the token against some basic rules.
This class uses the `spomky-labs/jose` library and returns an object which should make it possible for you to extract the necessary claims from the token header and payload. (https://github.com/Spomky-Labs/jose)

Let me know if you have any questions or suggestions.

**Comment by FerhanGit** [comment]
Thank you very much for the quick response on that topic! In this case I am gonna close the pull request.

**Comment by FerhanGit** [comment]
No more need of that pull request as the fix is already done by the project owner and a new version tagged.

**Pull request closed without merging**
